namespace WMS.domain.enumerate;

public enum ProductType
{
    ELECTRONICS,
    CLOTHES,
    SHOES,
    HOUSEHOLD_GOODS,
    BUILDING_MATERIALS,
    SPORTS_EQUIPMENT,
    ART_HOBBIES,
    TOOLS,
    OFFICE_SUPPLIES,
    BOOKS_EDUCATION,
    KITCHEN_SUPPLIES
}